import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'module'

	install_files('PREFIX',inst_dir,'MirrorModule.py')
	install_files('PREFIX',inst_dir,'TikiModule.py')
	install_files('PREFIX',inst_dir,'CalibrateModule.py')
	install_files('PREFIX',inst_dir,'Whiteboard.py')
