import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'module'

	install_files('PREFIX',inst_dir,'MirrorModule.py')
	install_files('PREFIX',inst_dir,'TikiMask.py')
	install_files('PREFIX',inst_dir,'CalibrateModule.py')
	install_files('PREFIX',inst_dir,'Whiteboard.py')
	install_files('PREFIX',inst_dir,'LaserPresenter.py')

	# line of demarcation

	install_files('PREFIX',inst_dir,'ShadowModule.py')
	install_files('PREFIX',inst_dir,'CatchOSIfUCan.py')
	install_files('PREFIX',inst_dir,'SoundMosaic.py')
	install_files('PREFIX',inst_dir,'PymunkModule.py')
	install_files('PREFIX',inst_dir,'LaserPointerTest.py')

