import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'input'

	install_files('PREFIX',inst_dir,'CameraInputProvider.py')
	install_files('PREFIX',inst_dir,'FlipInputProvider.py')
	install_files('PREFIX',inst_dir,'CVCameraInputProvider.py')
	install_files('PREFIX',inst_dir,'FaceInputProvider.py')
	install_files('PREFIX',inst_dir,'ShadowInputProvider.py')
