import os

def set_options(opt): pass

def configure(conf):
	conf.check_python_module('pygame')
	conf.check_python_module('ocempgui')
	conf.check_python_module('opencv')

def build(bld):

	inst_dir='aether'+os.sep+'core'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'AetherSettings.py')
	install_files('PREFIX',inst_dir,'AetherDriver.py')
	install_files('PREFIX',inst_dir,'AetherModule.py')
	install_files('PREFIX',inst_dir,'AetherParamModule.py')
	install_files('PREFIX',inst_dir,'InputProvider.py')
	install_files('PREFIX',inst_dir,'CameraInputProvider.py')
	install_files('PREFIX',inst_dir,'FaceInputProvider.py')
