import os

def set_options(opt):
	opt.sub_options('input')

def configure(conf):
	conf.check_python_module('opencv')

	conf.sub_config('input')

def build(bld):

	inst_dir='aether'+os.sep+'core'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_driver.py')
	install_files('PREFIX',inst_dir,'_module.py')
	install_files('PREFIX',inst_dir,'_param_module.py')
	install_files('PREFIX',inst_dir,'_input_provider.py')
	install_files('PREFIX',inst_dir,'CameraInputProvider.py')
	install_files('PREFIX',inst_dir,'FaceInputProvider.py')

	bld.add_subdirs('input')
