import os

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	inst_dir='aether'+os.sep+'error'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'AetherCameraError.py')
