import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'chain'

	install_files('PREFIX',inst_dir,'ScaledCameraChain.py')
	install_files('PREFIX',inst_dir,'FacesChain.py')
	install_files('PREFIX',inst_dir,'PerspectiveChain.py')
	install_files('PREFIX',inst_dir,'LaserPointerChain.py')

	# line of demarcation

	install_files('PREFIX',inst_dir,'ShadowPolyChain.py')
	install_files('PREFIX',inst_dir,'MouseChain.py')
	install_files('PREFIX',inst_dir,'DebugLaserPointerChain.py')
