import os

def set_options(opt):
	opt.sub_options('core')
	opt.sub_options('modules')
	opt.sub_options('util')
	opt.sub_options('error')
	opt.sub_options('sprites')

def configure(conf):
	conf.sub_config('core')
	conf.sub_config('modules')
	conf.sub_config('util')
	conf.sub_config('error')
	conf.sub_config('sprites')

def build(bld):

	inst_dir='aether'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_aether.py')

	bld.add_subdirs('core')
	bld.add_subdirs('modules')
	bld.add_subdirs('util')
	bld.add_subdirs('error')
	bld.add_subdirs('sprites')
