import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'transform'

	install_files('PREFIX',inst_dir,'CameraTransform.py')
	install_files('PREFIX',inst_dir,'FlipTransform.py')
	install_files('PREFIX',inst_dir,'CVCameraTransform.py')
	install_files('PREFIX',inst_dir,'FaceTransform.py')
	install_files('PREFIX',inst_dir,'ShadowTransform.py')
