import os

def set_options(opt): pass

def configure(conf): pass

def build(bld):

	inst_dir='aether'+os.sep+'transform'

	install_files('PREFIX',inst_dir,'CVMatPyGameSurface.py')
	install_files('PREFIX',inst_dir,'CVFlip.py')
	install_files('PREFIX',inst_dir,'CVTColor.py')
	install_files('PREFIX',inst_dir,'CVResize.py')
	install_files('PREFIX',inst_dir,'CVCamera.py')
	install_files('PREFIX',inst_dir,'CVBiggestFaces.py')
	install_files('PREFIX',inst_dir,'ShadowTransform.py')
